name: copilot-run-integration-tests

on:
  workflow_dispatch:
    inputs:
      BACKEND_HOST:
        required: true
        type: string
  workflow_call:
    inputs:
      BACKEND_HOST:
        required: true
        type: string

permissions:
  contents: read

jobs:
  tests:
    name: Integration Testing
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run integration tests
        env:
          BaseServerUrl: "https://${{inputs.BACKEND_HOST}}.azurewebsites.net/"
          Authority: "https://login.microsoftonline.com/${{secrets.COPILOT_CHAT_TEST_TENANT_ID}}"
          ClientID: ${{secrets.COPILOT_CHAT_TEST_APP_AAD_WEBAPP_CLIENT_ID}}
          Username: ${{secrets.COPILOT_CHAT_TEST_USER_ACCOUNT1}}
          Password: ${{secrets.COPILOT_CHAT_TEST_USER_PASSWORD1}}
          Scopes: "openid, offline_access, profile, api://${{secrets.COPILOT_CHAT_TEST_APP_AAD_WEBAPI_CLIENT_ID}}/access_as_user"
        run: dotnet test --logger trx
